# Generated by Django 5.0 on 2023-12-13 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('icon', models.ImageField(upload_to='icons/')),
                ('placement', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('android', 'ANDROID'), ('ios', 'IOS')], default='android', max_length=50, verbose_name='Platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
