# Generated by Django 5.0 on 2023-12-13 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('links', models.URLField()),
                ('icons', models.ImageField(upload_to='static/icons/')),
                ('platform', models.CharField(choices=[('android', 'ANDROID'), ('ios', 'IOS')], default='android', max_length=50, verbose_name='Platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('index', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'All Apps',
            },
        ),
        migrations.DeleteModel(
            name='AllApps',
        ),
    ]
