# Generated by Django 5.0 on 2023-12-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0006_alter_placement_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.apps'),
        ),
    ]
