# Generated by Django 5.0 on 2023-12-18 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0008_adnetwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraphes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('index', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.apps')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.adnetwork')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.placement')),
            ],
        ),
    ]
