# Generated by Django 5.0 on 2023-12-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0009_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='paragraphes',
            new_name='data',
        ),
    ]
